[project]
name = "optiviz"
version = "1.0.2"
description = "Educational tool for visualising PyTorch-compatible optimisers on any differentiable 1D or 2D function."
authors = [{ name = "Ronit Kunkolienker", email = "ronitkunk@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE.txt" }
requires-python = ">=3.8"
dependencies = [
    "torch",
    "matplotlib",
    "numpy",
    "flask",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["optiviz"]

[tool.setuptools.package-data]
optiviz = ["*.html"]